version: '2'

services:
  elasticsearch:
    build: ./
    networks:
      - app_tier
    environment:
      - "cluster.name=elastic-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: on-failure
    ports:
      - 9200:9200
    volumes:
      - es6-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.4
    networks:
      - app_tier
    environment:
      - "elasticsearch.url=http://elasticsearch:9200"
      - "elasticsearch.username=elastic"
      - "elasticsearch.password=changeme"
    ports:
      - 5601:5601

networks:
  app_tier:
    driver: bridge

volumes:
  es6-data:
